name = "Link Manager"
version = "0.1"
link = "https://github.com/HunterKing/Crankshaft-Link-Management"
source = "https://github.com/HunterKing/Crankshaft-Link-Management"
min-crankshaft-version = "0.2.2"

[author]
name = "Hunter King"
link = "https://github.com/HunterKing"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = true
	menu = false
	quick-access = false

[store]
description = """
Show/Hide links beneath Steam install button.
"""
